name: e2e-test

on:
  pull_request:
    branches: ["*"]

jobs:
  build_ios_for_e2e:
    type: build
    params:
      platform: ios # required
      profile: e2e-test # your eas build profile for E2E test

  maestro_test:
    needs: [build_ios_for_e2e]
    type: maestro
    params:
      build_id: ${{ needs.build_ios_for_e2e.outputs.build_id }} # required
      flow_path: ["./maestro/home-screen.yaml"] # required
